### ISSUE TITLE
Pipeline fails with PSR config merging failures

### ISSUE THREAD

**Issue by adamgoossens** [ploigos/ploigos-software-factory-operator#166]
When running the reference pipeline on the `0.2.7` version of the Operator, it will fail on the first PSR step with the following error:

```
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
specified -c/--config is invalid configuration: Error merging new sub step configuration into existing sub step configuration for sub step (Buildah) of step (create-container-image): Conflict at destination
```

It looks like this is due to our recent change to start removing the hardcoded reference app detail. The config for the `create-container-image` Buildah implementer has a different `destination` between the `ploigos-platform-config` ConfigMap and the pipeline `cicd/ploigos-platform-config/config.yml`. That causes a duplicate key conflict. Given this is a mismatch between what the Operator templates out, and the reference application, I've raised the issue against PSFO.

To solve this, should we start removing pipeline-specific configuration from the underlying `ploigos-platform-config` ConfigMap? e.g. specific Step Implementers that will likely change per-pipeline (such as Maven) and their associated configuration, promoting it into the reference app configuration?

We should also add another GHA step to deploy and verify a sample pipeline.

**Comment by andykrohg** [comment]
I left that property in the platform for the recent delivery because the local image destination only exists as a temporary tag before retagging and pushing to the configured image registry. I removed the override/conflict from the reference app so that should resolve the pipeline failure. As a matter of fact, it looks like that property is deprecated anyway - I don't see it anywhere in the step implemented. Looks like that can be safely removed: https://github.com/ploigos/ploigos-step-runner/blob/main/src/ploigos_step_runner/step_implementers/create_container_image/buildah.py

**Comment by adamgoossens** [comment]
Thanks, that'll clear the pipeline failure hurdle :) 

I'll take a look at what we can do in GHA to add a Pipeline test as well. I'll close off this issue now
